name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: swift-institute/.github/.github/workflows/swift-ci.yml@69e4306da2d0f3f4a3a5fa175beb8b0620e58da1
    secrets: inherit
